version: "3.9"
services:
  database:
    container_name: cts_mongodb
    image: mongo
    volumes:
      - cts_mongodb:/data/db
      - cts_mongodb_config:/data/config
    ports: 
      - "27017:27017"
  backend:
    container_name: cts_backend
    build: .
    volumes:
      - ${PWD}:/app
      - /app/node_modules
    ports:
      - "${BACKEND_BIND_PORT}:${BACKEND_PORT}"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DB_URI
      - PORT=${BACKEND_PORT}
  app:
    container_name: cts_front-app
    build: ${PWD}/../candidate-tracking-system/
    volumes: 
      - ${PWD}/../candidate-tracking-system:/app
      - /app/node_modules
    ports:
      - "${APP_BIND_PORT}:${APP_PORT}"
      - "6006:6006"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=${APP_PORT}
      - REACT_APP_API_URI="backend:${BACKEND_PORT}/"
volumes:
  cts_mongodb:
      name: cts_mongodb
  cts_mongodb_config:
      name: cts_mongodb_config
